name: Deploy to AWS EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ignus07/myportfolio .
        docker tag ignus07/myportfolio ignus07/myportfolio:latest
        docker push ignus07/myportfolio:latest

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.54.86.124.34 }}
        username: ${{ secrets.ubuntu }}
        key: ${{ secrets.-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
c2gtZWQyNTUxOQAAACAzE88n0k+AWAbxcaHUitoz8fqHIopfFefxgym5PFGcVgAA
AIjM2IC5zNiAuQAAAAtzc2gtZWQyNTUxOQAAACAzE88n0k+AWAbxcaHUitoz8fqH
IopfFefxgym5PFGcVgAAAEAwUQIBATAFBgMrZXAEIgQgQ3osfgxhmtrwrMV3rCo8
AjMTzyfST4BYBvFxodSK2jPx+ociil8V5/GDKbk8UZxWAAAAAAECAwQF
-----END OPENSSH PRIVATE KEY----- }}
        script: |
          docker pull ignus07/myportfolio:latest
          docker stop myportfolio || true
          docker rm myportfolio || true
          docker run -d -p 80:3000 --name myportfolio  ignus07/myportfolio:latest

